<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'pxlrbt\\CF7WeClapp\\Vendor\\pxlrbt\\WordpressNotifier\\' => array($vendorDir . '/pxlrbt/wordpress-notifier/src'),
    'pxlrbt\\CF7WeClapp\\Vendor\\Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'pxlrbt\\CF7WeClapp\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'pxlrbt\\CF7WeClapp\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => array($vendorDir . '/symfony/polyfill-intl-idn'),
    'pxlrbt\\CF7WeClapp\\Vendor\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'pxlrbt\\CF7WeClapp\\Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'pxlrbt\\CF7WeClapp\\Vendor\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'pxlrbt\\CF7WeClapp\\Vendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'pxlrbt\\CF7WeClapp\\Vendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'pxlrbt\\CF7WeClapp\\Vendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Pixelarbeit\\Wordpress\\' => array($baseDir . '/lib/Wordpress'),
    'Pixelarbeit\\WeClapp\\' => array($baseDir . '/lib/WeClapp'),
    'Pixelarbeit\\CF7WeClapp\\' => array($baseDir . '/classes'),
);
